#!/bin/sh
# Generated by legato — do not edit manually.
# Called by Claude Code hooks to update agent activity state.

# Only act inside Legato-spawned tmux sessions.
[ -z "$LEGATO_TASK_ID" ] && exit 0

/var/home/cameron/Projects/legato/legato agent state "$LEGATO_TASK_ID" --activity working
exit 0
