package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const staccatoScriptName = "legato-pr-link.sh"

// staccatoHookEvents lists the staccato events that trigger PR linking.
var staccatoHookEvents = []string{"post-pr-create", "post-pr-view"}

// StaccatoAdapter implements the AIToolAdapter interface for Staccato.
// It installs hooks for post-pr-create and post-pr-view that link the branch and repo to a task.
type StaccatoAdapter struct {
	legatoBin string
}

// NewStaccatoAdapter creates a Staccato adapter.
func NewStaccatoAdapter(legatoBin string) *StaccatoAdapter {
	return &StaccatoAdapter{legatoBin: legatoBin}
}

func (a *StaccatoAdapter) Name() string { return "staccato" }

func (a *StaccatoAdapter) EnvVars(taskID, socketPath string) map[string]string {
	// LEGATO_TASK_ID is already injected by the agent service into tmux sessions.
	// Staccato hooks read it from the environment directly.
	return nil
}

func (a *StaccatoAdapter) InstallHooks(projectDir string) error {
	script := prLinkScript(a.legatoBin)
	for _, event := range staccatoHookEvents {
		hookDir := staccatoHookDir(event)
		if err := os.MkdirAll(hookDir, 0o755); err != nil {
			return fmt.Errorf("creating staccato hooks directory for %s: %w", event, err)
		}
		path := filepath.Join(hookDir, staccatoScriptName)
		if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
			return fmt.Errorf("writing %s for %s: %w", staccatoScriptName, event, err)
		}
	}
	return nil
}

func (a *StaccatoAdapter) UninstallHooks(projectDir string) error {
	for _, event := range staccatoHookEvents {
		hookDir := staccatoHookDir(event)
		path := filepath.Join(hookDir, staccatoScriptName)
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("removing %s for %s: %w", staccatoScriptName, event, err)
		}
	}
	return nil
}

// staccatoHookDir returns the global staccato hooks directory for an event.
// Staccato hooks live in ~/.config/staccato/hooks/<event>/.
func staccatoHookDir(event string) string {
	configDir := os.Getenv("XDG_CONFIG_HOME")
	if configDir == "" {
		home, _ := os.UserHomeDir()
		configDir = filepath.Join(home, ".config")
	}
	return filepath.Join(configDir, "staccato", "hooks", event)
}

func prLinkScript(legatoBin string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by legato — do not edit manually.\n")
	b.WriteString("# Called by staccato hooks to link branch/repo to task.\n\n")
	b.WriteString("# Only act inside Legato-spawned tmux sessions.\n")
	b.WriteString("[ -z \"$LEGATO_TASK_ID\" ] && exit 0\n\n")
	b.WriteString("# Detect owner/repo from the repo's git remote.\n")
	b.WriteString("REMOTE=$(cd \"$ST_REPO_PATH\" && git remote get-url origin 2>/dev/null)\n")
	b.WriteString("OWNER_REPO=$(echo \"$REMOTE\" | sed -E 's|.*github\\.com[:/]([^/]+/[^/.]+)(\\.git)?$|\\1|')\n")
	b.WriteString("[ -z \"$OWNER_REPO\" ] && exit 0\n\n")
	b.WriteString(fmt.Sprintf("%s task link \"$LEGATO_TASK_ID\" --branch \"$ST_BRANCH\" --repo \"$OWNER_REPO\"\n", legatoBin))
	b.WriteString("exit 0\n")
	return b.String()
}
