import { useRef, useState } from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { ArrowLeft, Send } from "lucide-react"
import { Link, useNavigate, useParams } from "react-router-dom"
import { usePlan } from "../hooks/usePlan"
import { useServer } from "../hooks/useServer"
import { addPlanComment, askPlanQuestion, planAction, respondToPlanQuestion, type PlanOption, type PlanQuestion } from "../lib/plan"
import { ReviewMessageBody } from "../components/ReviewMessageBody"

export function PlanPage(){
 const {planId=""}=useParams(), id=decodeURIComponent(planId), {baseUrl}=useServer(), {data,loading,error,refresh}=usePlan(id), navigate=useNavigate()
 const markdownRef=useRef<HTMLDivElement>(null), [selection,setSelection]=useState<{start:number;end:number;text:string}|null>(null), [comment,setComment]=useState(""), [question,setQuestion]=useState(""), [busy,setBusy]=useState(false), [actionError,setActionError]=useState<string|null>(null), [info,setInfo]=useState<string|null>(null)
 async function run(action:()=>Promise<void>){setBusy(true);setActionError(null);try{await action();await refresh()}catch(c){setActionError(c instanceof Error?c.message:String(c))}finally{setBusy(false)}}
 function captureSelection(){ const selected=window.getSelection()?.toString()??""; if(!selected.trim()||!data)return; const start=data.revision.markdown.indexOf(selected); if(start>=0)setSelection({start,end:start+selected.length,text:selected}) }
 async function submitComment(){if(!comment.trim())return;await run(async()=>{await addPlanComment(baseUrl,id,{body:comment.trim(),...(selection?{selection_start:selection.start,selection_end:selection.end,selected_text:selection.text}:{})});setComment("");setSelection(null);window.getSelection()?.removeAllRanges()})}
 async function verdict(action:"request-changes"|"approve"|"reject"|"reopen"){await run(async()=>{await planAction(baseUrl,id,action);if(action!=="reopen")navigate("/plans")})}
 async function ask(){if(!question.trim())return;await run(async()=>{const result=await askPlanQuestion(baseUrl,id,question.trim());setQuestion("");setInfo(result.warning??"Question sent")})}
 if(loading&&!data)return <div className="p-6 text-zinc-500">Loading plan…</div>;if(error&&!data)return <div className="p-6 text-red-300">{error}</div>;if(!data)return null
 const unanswered=data.questions.filter(q=>q.required&&!data.responses.some(r=>r.question_id===q.id)).length
 return <div className="flex h-full min-h-0 flex-col bg-[#0a0a0f] text-zinc-200">
  <header className="flex items-center justify-between border-b border-zinc-800 px-5 py-3"><div><Link to="/plans" className="flex items-center gap-1 text-xs text-zinc-500"><ArrowLeft size={13}/> Plan queue</Link><h1 className="mt-1 text-lg font-semibold">{data.plan.title}</h1><div className="text-xs text-zinc-500">revision {data.plan.latest_revision} · {data.plan.status.replace("_"," ")}</div></div><div className="flex gap-2">{data.plan.status==="proposed"&&<><button disabled={busy} onClick={()=>void verdict("reject")} className="rounded border border-red-900 px-3 py-1.5 text-xs text-red-300">Reject</button><button disabled={busy} onClick={()=>void verdict("request-changes")} className="rounded border border-amber-800 px-3 py-1.5 text-xs text-amber-300">Request changes</button><button title={unanswered?"Answer required choices first":"Approve plan"} disabled={busy||unanswered>0} onClick={()=>void verdict("approve")} className="rounded bg-emerald-700 px-3 py-1.5 text-xs text-white disabled:opacity-40">Approve plan</button></>}{data.plan.status==="rejected"&&<button onClick={()=>void verdict("reopen")} className="rounded bg-indigo-600 px-3 py-1.5 text-xs">Reopen</button>}</div></header>
  {actionError&&<div role="alert" className="border-b border-red-900 bg-red-950/40 px-5 py-2 text-xs text-red-300">{actionError}</div>}{info&&<div className="border-b border-zinc-800 px-5 py-2 text-xs text-zinc-400">{info}</div>}
  <div className="grid min-h-0 flex-1 grid-cols-1 lg:grid-cols-[minmax(0,1fr)_25rem]">
   <main className="overflow-y-auto p-6"><div className="mx-auto max-w-3xl space-y-5">
    <article ref={markdownRef} onMouseUp={captureSelection} className="rounded border border-zinc-800 bg-zinc-950 p-6 leading-7"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{h1:({children})=><h1 className="mb-5 text-2xl font-bold">{children}</h1>,h2:({children})=><h2 className="mb-3 mt-6 text-xl font-semibold">{children}</h2>,p:({children})=><p className="my-3 text-zinc-300">{children}</p>,ul:({children})=><ul className="my-3 list-disc pl-6">{children}</ul>,ol:({children})=><ol className="my-3 list-decimal pl-6">{children}</ol>,code:({children})=><code className="rounded bg-black/40 px-1 font-mono text-sm">{children}</code>}}>{data.revision.markdown}</ReactMarkdown></article>
    {data.comments.length>0&&<section><h2 className="mb-2 text-sm font-semibold text-zinc-400">Feedback</h2><div className="space-y-2">{data.comments.map(c=><div key={c.id} className="rounded border border-indigo-900 bg-indigo-950/20 p-3 text-sm">{c.selected_text&&<blockquote className="mb-2 border-l-2 border-indigo-600 pl-2 text-zinc-500">{c.selected_text}</blockquote>}<p>{c.body}</p><span className="text-[10px] uppercase text-zinc-600">{c.submitted_at?"submitted":"draft"} · revision {c.revision_id===data.revision.id?data.revision.revision:"prior"}</span></div>)}</div></section>}
   </div></main>
   <aside className="flex min-h-0 flex-col overflow-y-auto border-l border-zinc-800 bg-zinc-950 p-4"><h2 className="text-xs font-semibold uppercase text-zinc-500">Choices</h2><div className="mt-3 space-y-4">{data.questions.map(q=><PlanQuestionControl key={q.id} question={q} response={data.responses.find(r=>r.question_id===q.id)} disabled={busy} onRespond={body=>run(()=>respondToPlanQuestion(baseUrl,id,q.key,body))}/>)}</div>
    <div className="mt-6 border-t border-zinc-800 pt-4"><h2 className="text-xs font-semibold uppercase text-zinc-500">Comment on plan</h2>{selection&&<div className="mt-2 rounded bg-indigo-950/40 p-2 text-xs text-indigo-200">“{selection.text}” <button onClick={()=>setSelection(null)} className="ml-2 text-zinc-500">clear</button></div>}<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder={selection?"Comment on selected text…":"Leave general feedback…"} className="mt-2 w-full rounded border border-zinc-700 bg-zinc-900 p-2 text-sm"/><button disabled={busy||!comment.trim()} onClick={()=>void submitComment()} className="mt-2 rounded bg-indigo-600 px-3 py-1.5 text-xs disabled:opacity-40">Add draft comment</button></div>
    <div className="mt-6 border-t border-zinc-800 pt-4"><h2 className="text-xs font-semibold uppercase text-zinc-500">Questions & answers</h2><div className="my-3 space-y-2">{data.messages.map(m=><div key={m.id} className={`rounded p-2 ${m.author==="user"?"bg-indigo-950/40":"bg-zinc-900"}`}><ReviewMessageBody body={m.body}/></div>)}</div><div className="flex gap-2"><textarea value={question} onChange={e=>setQuestion(e.target.value)} className="min-w-0 flex-1 rounded border border-zinc-700 bg-zinc-900 p-2 text-sm" placeholder="Ask the agent…"/><button disabled={busy||!question.trim()} onClick={()=>void ask()} className="rounded bg-zinc-800 p-2"><Send size={15}/></button></div></div>
   </aside>
  </div>
 </div>
}

function PlanQuestionControl({question,response,disabled,onRespond}:{question:PlanQuestion;response?:{values_json:string;text:string};disabled:boolean;onRespond:(body:{values?:string[];text?:string})=>Promise<void>}){
 const options=JSON.parse(question.options_json||"[]") as PlanOption[], selected=response?JSON.parse(response.values_json||"[]") as string[]:[], [text,setText]=useState(response?.text??"")
 if(question.kind==="free_text")return <div><label className="text-sm text-zinc-200">{question.prompt}{question.required&&<span className="text-amber-400"> *</span>}</label><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-2 w-full rounded border border-zinc-700 bg-zinc-900 p-2 text-sm"/><button disabled={disabled||!text.trim()} onClick={()=>void onRespond({text})} className="mt-1 text-xs text-indigo-300">Save answer</button></div>
 return <fieldset><legend className="text-sm">{question.prompt}{question.required&&<span className="text-amber-400"> *</span>}</legend><div className="mt-2 space-y-1">{options.map(o=><label key={o.id} className="flex gap-2 text-sm text-zinc-400"><input type={question.kind==="single_choice"?"radio":"checkbox"} name={question.id} checked={selected.includes(o.id)} disabled={disabled} onChange={()=>void onRespond({values:question.kind==="single_choice"?[o.id]:selected.includes(o.id)?selected.filter(v=>v!==o.id):[...selected,o.id]})}/><span>{o.label}{o.description&&<small className="block text-zinc-600">{o.description}</small>}</span></label>)}</div></fieldset>
}
